name: "Daniel Samuels"
description: "Software developer based in Cambridge"
highlighter: pygments

url: "http://danielsamuels.co.uk"

# paginate: 10
permalinks: pretty

defaults:
    -
        values:
            author: "Daniel Samuels"
            layout: content
