name: "Daniel Finch"
description: "Software developer based in Cambridge"
highlighter: rouge

url: "http://danielsamuels.co.uk"

# paginate: 10
permalink: /words/:year/:month/:day/:title/

defaults:
    -
        values:
            author: "Daniel Finch"
            layout: content
